### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by vladsavelyev** [crukci-bioinformatics/gatk-tools#1]
Hi Matt,

When I run `mvn package`, I'm getting `BUILD FAILURE` right after the attempt to download
`gatk-3.7.pom`:
``` 
[~/git/gatk-tools]$ mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building GATK Tools 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading from bioinformatics: http://internal-bioinformatics.cruk.cam.ac.uk/maven/org/broadinstitute/gatk/gatk/3.7/gatk-3.7.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.723 s
[INFO] Finished at: 2017-10-27T15:19:20+11:00
[INFO] Final Memory: 11M/38M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project gatk-tools: Could not resolve dependencies for project org.cruk.gatk:gatk-tools:jar:1.0-SNAPSHOT: Failed to collect dependencies at org.broadinstitute.gatk:gatk:jar:3.7: Failed to read artifact descriptor for org.broadinstitute.gatk:gatk:jar:3.7: Could not transfer artifact org.broadinstitute.gatk:gatk:pom:3.7 from/to bioinformatics (http://internal-bioinformatics.cruk.cam.ac.uk/maven): internal-bioinformatics.cruk.cam.ac.uk: nodename nor servname provided, or not known: Unknown host internal-bioinformatics.cruk.cam.ac.uk: nodename nor servname provided, or not known -> [Help 1]
```

And indeed, http://internal-bioinformatics.cruk.cam.ac.uk/maven/org/broadinstitute/gatk/gatk/3.7/gatk-3.7.pom is not reachable.

I'm not familiar with maven, so maybe I have something misconfigured. Can you please suggest how do I go on from here?

**Comment by ohofmann** [comment]
Matt, Vlad works with Brad and me; we're finally getting around to revisiting our (ancient!) discussion around panels of normals in SNVs and SVs.

**Comment by eldrid01** [comment]
HI Vlad, Oliver,

Did you install the GATK jar in your maven repository?

Sadly the current stable release of GATK 3.8 is not available through the central maven repository so you have to download that from the GATK website and install the jar file with mvn install:

mvn install:install-file -Dpackaging=jar -DgroupId=org.broadinstitute.gatk -DartifactId=gatk -Dversion=3.8 -Dfile=GenomeAnalysisTK.jar

You should then have the file available for the maven build in the following location:
~/.m2/repository/org/broadinstitute/gatk/gatk/3.8/gatk-3.8.jar

Also because of the restrictive license in place until recently the GATK jar does not get packaged with the gatk-tools tarball so you have to set an environment variable, CLASSPATH_PREFIX, prior to running either of the two tools:

export CLASSPATH_PREFIX=.m2/repository/org/broadinstitute/gatk/gatk/3.8/gatk-3.8.jar

All this will change with the upcoming GATK v4 in which the Broad have dropped their restrictive licensing terms and have been pushing their alpha and beta releases to the central maven repository. There are however some substantial changes to the API and namespaces and updating the gatk-tools package to work with GATK 4 will require some work.

Cheers,
Matt

**Comment by vladsavelyev** [comment]
Matt,

I was following the README instructions, so I downloaded `GenomeAnalysisTK.jar` and out it into the repository and ran the command to install it:
```
mvn install:install-file -Dpackaging=jar -DgroupId=org.broadinstitute.gatk -DartifactId=gatk -Dversion=3.8 -Dfile=GenomeAnalysisTK.jar
```
Which finished successfully.

However the following `mvn package` command is giving me the error :(

**Comment by eldrid01** [comment]
Hi Vlad,

It appears to be a problem with including our internal repositories in the maven pom file. Although I wasn't able to reproduce the problem you're seeing on my home computer which also doesn't have access to our work network, I've removed the repository section to see if this helps. Please can you try again?

Thanks,
Matt

**Comment by vladsavelyev** [comment]
Yes, it works now! 

Thanks a lot Matt.
